// Core Actions
export const CORE_WORKSPACE_IDS_CHANGE = 'CORE_WORKSPACE_IDS_CHANGE';
export const CORE_WORKSPACES_CHANGE = 'CORE_WORKSPACES_CHANGE';
export const CORE_CHANNEL_IDS_CHANGE = 'CORE_CHANNEL_IDS_CHANGE';
export const CORE_CHANNELS_CHANGE = 'CORE_CHANNELS_CHANGE';
export const CORE_MEMO_IDS_CHANGE = 'CORE_MEMO_IDS_CHANGE';
export const CORE_MEMOS_CHANGE = 'CORE_MEMOS_CHANGE';
export const CORE_SELECTED_WORKSPACE_ID_CHANGE = 'CORE_SELECTED_WORKSPACE_ID_CHANGE';
export const CORE_SELECTED_CHANNEL_ID_CHANGE = 'CORE_SELECTED_CHANNEL_ID_CHANGE';
export const CORE_SELECTED_MEMO_ID_CHANGE = 'CORE_SELECTED_MEMO_ID_CHANGE';
